kind: ConfigMap
apiVersion: v1
metadata:
  name: olm-operators
  namespace: openshift-operator-lifecycle-manager

data:
  customResourceDefinitions: |-
  clusterServiceVersions: |-
    
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: packageserver.v4.0.0-olm
        namespace: openshift-operator-lifecycle-manager
      spec:
        displayName: Package Server
        description: Represents an Operator package that is available from a given CatalogSource which will resolve to a ClusterServiceVersion.
        minKubeVersion: 1.11.0
        keywords: ['packagemanifests', 'olm', 'packages']
        maintainers:
        - name: Red Hat
          email: openshift-operators@redhat.com
        provider:
          name: Red Hat
        links:
        - name: Package Server
          url: https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/package-server
        installModes:
        - type: OwnNamespace
          supported: true
        - type: SingleNamespace
          supported: true
        - type: MultiNamespace
          supported: true
        - type: AllNamespaces
          supported: true
        install:
          strategy: deployment
          spec:
            clusterPermissions:
            - serviceAccountName: packageserver
              rules:
              - apiGroups:
                - ""
                resources:
                - configmaps
                verbs:
                - get
                - list
                - watch
              - apiGroups:
                - "operators.coreos.com"
                resources:
                - catalogsources
                verbs:
                - get
                - list
                - watch
              - apiGroups:
                - "packages.apps.redhat.com"
                resources:
                - packagemanifests
                verbs:
                - get
                - list
            deployments:
            - name: packageserver
              spec:
                replicas: 2
                strategy:
                  type: RollingUpdate
                selector:
                  matchLabels:
                    app: packageserver
                template:
                  metadata:
                    labels:
                      app: packageserver
                  spec:
                    serviceAccountName: packageserver
                    nodeSelector:
                      beta.kubernetes.io/os: linux
                      
                    tolerations:
                      - operator: Exists
                      
                    containers:
                    - name: packageserver
                      command:
                      - /bin/package-server
                      - -v=4
                      - --secure-port
                      - "5443"
                      - --global-namespace
                      - openshift-operator-lifecycle-manager
                      image: quay.io/openshift/origin-operator-lifecycle-manager:latest
                      imagePullPolicy: Always
                      ports:
                      - containerPort: 5443
                      livenessProbe:
                          httpGet:
                            scheme: HTTPS
                            path: /healthz
                            port: 5443
                      readinessProbe:
                          httpGet:
                            scheme: HTTPS
                            path: /healthz
                            port: 5443
        maturity: alpha
        version: 4.0.0-olm
        apiservicedefinitions:
          owned:
          - group: packages.apps.redhat.com
            version: v1alpha1
            kind: PackageManifest
            name: packagemanifests
            displayName: PackageManifest
            description: A PackageManifest is a resource generated from existing CatalogSources and their ConfigMaps
            deploymentName: packageserver
            containerPort: 5443
  packages: |-
    
    - packageName: packageserver
      channels:
      - name: alpha
        currentCSV: packageserver.v4.0.0-olm

