apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: olm-operators
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: configmap
  configMap: olm-operators
  displayName: OLM Operators
  publisher: Red Hat